#[Info]
site_name: 李烨栋的博客   #网站名字
site_description: 美少男
site_author: 李烨栋 #作者名
site_url: https://li-ye-dong.github.io/  #网站地址
copyright: Copyright &copy; 2025 李烨栋 # 左下角的版权声明

## [Navigtion]
# nav:
#   - 首页: index.md
#   - 快速开始: 快速开始/快速开始.md
#   - 通用岗: 通用岗/通用岗.md
#   - 通用数据岗: 通用数据岗/通用数据岗.md
#   - 硬件岗: 硬件岗/硬件岗.md
#   - 软件岗: 软件岗/软件岗.md
#   - 硬件测试岗: 硬件测试岗/硬件测试岗.md
#   - 产线岗: 产线岗/产线岗.md
#   - 常见问题: 常见问题/常见问题.md
#   - 更新记录:
#       - blog/index.md

nav:
  - Home: index.md
  - Redis:
    - redis/Redis学习.md
    #- 设计模式: java/设计模式/index.md
  - Dokcer:
    - docker/docker笔记.md
 #   - Installation: guide/installation.md
 #   - Basics: guide/basics.md
 #   - Configuration: guide/config.md
  - Nginx:
    - nginx/Nginx学习.md
  - MySQL:
    - mysql8/mysql8学习.md
  - Blog:
      - blog/index.md




#[UI]
theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  font: false  # 禁用 Google Fonts
  # favicon: static/logo.png
#  font:
#    text: Roboto
#    code: Roboto Mono
  # logo: static/logo.png
#  favicon: static/logo.png
#  logo: static/logo.png

  features:
    - header.autohide  #自动隐藏
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    #- navigation.instant #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.expand # 打开Tab时左侧目录全部展开
    - content.code.copy
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      toggle:
        icon: material/brightness-7  # 图标
        name: 日间模式
      primary: green # 上方的, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: green # # 链接等可交互元件的高亮色 [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: blue #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: blue # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: 夜间模式

  icon:
    repo: fontawesome/brands/github #右上角图标
repo_name: li-ye-dong.github.io # 右上角的名
repo_url: https://github.com/li-ye-dong/liyedong.github.io.git # 右上角点击跳转的链接


markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      title: 在这个页面
      slugify: !!python/name:pymdownx.slugs.uslugify  #MkDocs 兼容中文锚点 已经弃用
      #slugify: !!python/name:pymdownx.slugs.slugify_unicode
      #slugify: !!python/name:pymdownx.slugs.slugify_case
      #slugify: !!python/name:pymdownx.slugs.slugify
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # 代码块高亮插件
      custom_fences:
          - name: mermaid
            class: mermaid
            format:
              !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables

#extra_javascript:
#  - javascripts/extra.js
  #- javascripts/mathjax.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - static/stylesheets/google_font.css


extra:
  static_dir: [static]  #自定义静态文件目录  通过markdown格式 [下载 ZIP](static/myfile.zip)
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
    # social:
    #  - icon: fontawesome/brands/twitter
    #    link: https://twitter.com/
    #  - icon: fontawesome/brands/github
    #    link: https://github.com/
    #  - icon: fontawesome/brands/bilibili
    #    link: https://space.bilibili.com/
    #  - icon: fontawesome/solid/paper-plane
    #    link: mailto:<xxxxxx@qq.com> #联系方式
    #

    #  analytics:
    #    provider: google
    #    property: G-XXXXXXXXXX # Google Analytics ID
    #    feedback:
    #      title: 此页面有帮助吗？
    #      ratings:
    #        - icon: material/thumb-up-outline
    #          name: This page was helpful
    #          data: 1
    #          note: >-
    #            谢谢你的反馈！
    #        - icon: material/thumb-down-outline
    #          name: This page could be improved
    #          data: 0
    #          note: >-
    #            Thanks for your feedback! Help us improve this page by
    #            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
    #
    #  consent:
    #    title: Cookie consent
    #    description: >-
    #      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
    #      如果你同意,你可以帮助我们让我们的网站更好


plugins:
  - blogging:
      dirs:
        - blog
      locale: zh_CN  # 这里强制设定中文
  - search

#       post_date_format: full #时间
#       draft: true
#       draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
#       post_readtime: true
#       post_readtime_words_per_minute: 265 #计算帖子的阅读时间时读者每分钟预计阅读的字数
#       post_url_format: "{date}/{slug}"
#       # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
#       #   kwds:
#       #     case: lower
#       pagination_url_format: "page/{page}"
#       authors_file: "{blog}/.authors.yml" #作者信息
#   - tags:
  # tags_file: tag.md #标签
